// Code generated by "stringer -type=exifType"; DO NOT EDIT.

package imagemeta

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[exitTypeUnsignedByte-1]
	_ = x[exitTypeUnsignedASCII-2]
	_ = x[exitTypeUnsignedShort-3]
	_ = x[exitTypeUnsignedLong-4]
	_ = x[exitTypeUnsignedRat-5]
	_ = x[exitTypeSignedByte-6]
	_ = x[exitTypeUndef-7]
	_ = x[exitTypeSignedShort-8]
	_ = x[exitTypeSignedLong-9]
	_ = x[exitTypeSignedRat-10]
	_ = x[exitTypeSignedFloat-11]
	_ = x[exitTypeSignedDouble-12]
}

const _exifType_name = "exitTypeUnsignedByteexitTypeUnsignedASCIIexitTypeUnsignedShortexitTypeUnsignedLongexitTypeUnsignedRatexitTypeSignedByteexitTypeUndefexitTypeSignedShortexitTypeSignedLongexitTypeSignedRatexitTypeSignedFloatexitTypeSignedDouble"

var _exifType_index = [...]uint8{0, 20, 41, 62, 82, 101, 119, 132, 151, 169, 186, 205, 225}

func (i exifType) String() string {
	i -= 1
	if i >= exifType(len(_exifType_index)-1) {
		return "exifType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _exifType_name[_exifType_index[i]:_exifType_index[i+1]]
}
