// Code generated by "stringer -type=ImageFormat"; DO NOT EDIT.

package imagemeta

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ImageFormatAuto-0]
	_ = x[ImageFormatJPEG-1]
	_ = x[ImageFormatWebP-2]
}

const _ImageFormat_name = "ImageFormatAutoImageFormatJPEGImageFormatWebP"

var _ImageFormat_index = [...]uint8{0, 15, 30, 45}

func (i ImageFormat) String() string {
	if i < 0 || i >= ImageFormat(len(_ImageFormat_index)-1) {
		return "ImageFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ImageFormat_name[_ImageFormat_index[i]:_ImageFormat_index[i+1]]
}
