// Code generated by "stringer -type=TagSource"; DO NOT EDIT.

package imagemeta

import "strconv"

const _TagSource_name = "TagSourceEXIFTagSourceIPTCTagSourceXMP"

var _TagSource_index = [...]uint8{0, 13, 26, 38}

func (i TagSource) String() string {
	if i < 0 || i >= TagSource(len(_TagSource_index)-1) {
		return "TagSource(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TagSource_name[_TagSource_index[i]:_TagSource_index[i+1]]
}

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TagSourceEXIF-0]
	_ = x[TagSourceIPTC-1]
	_ = x[TagSourceXMP-2]
}
